#!/usr/bin/env bash
# ==============================================================================
# f5xc-gcp-iam-setup.sh
#
# One-time bootstrap for the GCP IAM role + service account that F5XC needs
# to create/manage a GCP VPC site, per F5's reference doc:
#   https://docs.cloud.f5.com/docs-v2/multi-cloud-network-connect/reference/cloud-cred-ref/gcp-vpc-cred-ref
#
# This script does NOT touch the Terraform config. It just performs the
# manual gcloud steps from that doc (create role -> create SA -> bind role ->
# create key) and then writes the result into the TF_VAR_* names this repo
# already reads (gcp_service_account_key_b64, gcp_project_id) plus
# GOOGLE_APPLICATION_CREDENTIALS for the google provider itself.
#
# Usage:
#   export GCP_PROJECT=my-project-id
#   export GCP_ROLE_ID=xcs_gcp_vpc_role
#   export GCP_ACCOUNT_ID=xcs-gcp-vpc-spn
#   ./f5xc-gcp-iam-setup.sh
#
#   source .f5xc-env.sh        # generated by this script
#   terraform plan
#
# Re-running is safe: existing role/SA are reused and the role permissions
# are updated in place.
# ==============================================================================

set -euo pipefail

: "${GCP_PROJECT:?Set GCP_PROJECT to your GCP project ID}"
: "${GCP_ROLE_ID:?Set GCP_ROLE_ID to the custom role ID, e.g. xcs_gcp_vpc_role}"
: "${GCP_ACCOUNT_ID:?Set GCP_ACCOUNT_ID to the service account name, e.g. xcs-gcp-vpc-spn}"

KEY_FILE="${KEY_FILE:-./sa-key.json}"
ENV_FILE="${ENV_FILE:-./.f5xc-env.sh}"
ROLE_YAML="$(mktemp /tmp/f5xc_gcp_vpc_role.XXXXXX.yaml)"
trap 'rm -f "${ROLE_YAML}"' EXIT

command -v gcloud >/dev/null 2>&1 || {
  echo "gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install" >&2
  exit 1
}

echo "==> Project:          ${GCP_PROJECT}"
echo "==> Role ID:           ${GCP_ROLE_ID}"
echo "==> Service account:   ${GCP_ACCOUNT_ID}"
echo

# ------------------------------------------------------------------
# 1. Role definition - permissions per F5's published GCP VPC site
#    requirements. If F5 updates the permission list, edit this block
#    (or swap it for their YAML: https://gitlab.com/volterra.io/cloud-credential-templates/-/blob/master/gcp/f5xc_gcp_vpc_role.yaml)
# ------------------------------------------------------------------
cat > "${ROLE_YAML}" <<'EOF'
title: "F5XC GCP VPC Site Role"
description: "Permissions required for F5 Distributed Cloud to create/manage a GCP VPC site"
stage: "GA"
includedPermissions:
  - compute.addresses.create
  - compute.addresses.delete
  - compute.addresses.get
  - compute.addresses.use
  - compute.backendServices.create
  - compute.backendServices.delete
  - compute.backendServices.get
  - compute.backendServices.list
  - compute.disks.create
  - compute.disks.delete
  - compute.disks.get
  - compute.disks.list
  - compute.disks.resize
  - compute.disks.setLabels
  - compute.firewalls.create
  - compute.firewalls.delete
  - compute.firewalls.get
  - compute.firewalls.list
  - compute.firewalls.update
  - compute.forwardingRules.create
  - compute.forwardingRules.delete
  - compute.forwardingRules.get
  - compute.forwardingRules.list
  - compute.forwardingRules.setLabels
  - compute.globalOperations.get
  - compute.healthChecks.create
  - compute.healthChecks.delete
  - compute.healthChecks.get
  - compute.healthChecks.list
  - compute.healthChecks.useReadOnly
  - compute.images.create
  - compute.images.get
  - compute.images.list
  - compute.images.useReadOnly
  - compute.instanceGroupManagers.create
  - compute.instanceGroupManagers.delete
  - compute.instanceGroupManagers.get
  - compute.instanceGroupManagers.list
  - compute.instanceGroupManagers.update
  - compute.instanceGroups.create
  - compute.instanceGroups.delete
  - compute.instanceGroups.get
  - compute.instanceGroups.list
  - compute.instanceGroups.use
  - compute.instanceTemplates.create
  - compute.instanceTemplates.delete
  - compute.instanceTemplates.get
  - compute.instanceTemplates.list
  - compute.instanceTemplates.useReadOnly
  - compute.instances.attachDisk
  - compute.instances.create
  - compute.instances.delete
  - compute.instances.deleteAccessConfig
  - compute.instances.detachDisk
  - compute.instances.get
  - compute.instances.list
  - compute.instances.reset
  - compute.instances.resume
  - compute.instances.setLabels
  - compute.instances.setMachineResources
  - compute.instances.setMachineType
  - compute.instances.setMetadata
  - compute.instances.setServiceAccount
  - compute.instances.setTags
  - compute.instances.start
  - compute.instances.stop
  - compute.instances.update
  - compute.instances.updateAccessConfig
  - compute.instances.updateNetworkInterface
  - compute.instances.use
  - compute.interconnectAttachments.get
  - compute.machineTypes.list
  - compute.machineTypes.get
  - compute.networkEndpointGroups.attachNetworkEndpoints
  - compute.networks.access
  - compute.networks.create
  - compute.networks.delete
  - compute.networks.get
  - compute.networks.list
  - compute.networks.update
  - compute.networks.updatePolicy
  - compute.networks.use
  - compute.networks.useExternalIp
  - compute.projects.get
  - compute.regionBackendServices.create
  - compute.regionBackendServices.delete
  - compute.regionBackendServices.get
  - compute.regionBackendServices.list
  - compute.regionBackendServices.use
  - compute.regions.get
  - compute.regionOperations.get
  - compute.routes.create
  - compute.routes.delete
  - compute.routes.get
  - compute.routes.list
  - compute.routers.get
  - compute.subnetworks.create
  - compute.subnetworks.delete
  - compute.subnetworks.get
  - compute.subnetworks.list
  - compute.subnetworks.setPrivateIpGoogleAccess
  - compute.subnetworks.update
  - compute.subnetworks.use
  - compute.subnetworks.useExternalIp
  - compute.zones.get
  - iam.serviceAccounts.actAs
  - iam.serviceAccounts.get
  - iam.serviceAccounts.list
  - resourcemanager.projects.get
EOF

# ------------------------------------------------------------------
# 2. Create (or update) the custom role
# ------------------------------------------------------------------
if gcloud iam roles describe "${GCP_ROLE_ID}" --project="${GCP_PROJECT}" >/dev/null 2>&1; then
  echo "==> Role ${GCP_ROLE_ID} already exists - updating permissions..."
  gcloud iam roles update "${GCP_ROLE_ID}" --project="${GCP_PROJECT}" --file="${ROLE_YAML}"
else
  echo "==> Creating role ${GCP_ROLE_ID}..."
  gcloud iam roles create "${GCP_ROLE_ID}" --project="${GCP_PROJECT}" --file="${ROLE_YAML}"
fi

# ------------------------------------------------------------------
# 3. Create (or reuse) the service account
# ------------------------------------------------------------------
SA_EMAIL="${GCP_ACCOUNT_ID}@${GCP_PROJECT}.iam.gserviceaccount.com"

if gcloud iam service-accounts describe "${SA_EMAIL}" --project="${GCP_PROJECT}" >/dev/null 2>&1; then
  echo "==> Service account ${SA_EMAIL} already exists - reusing."
else
  echo "==> Creating service account ${GCP_ACCOUNT_ID}..."
  gcloud iam service-accounts create "${GCP_ACCOUNT_ID}" \
    --project="${GCP_PROJECT}" \
    --display-name="${GCP_ACCOUNT_ID}"
fi

# ------------------------------------------------------------------
# 4. Bind the role to the service account
# ------------------------------------------------------------------
echo "==> Binding projects/${GCP_PROJECT}/roles/${GCP_ROLE_ID} to ${SA_EMAIL}..."
gcloud projects add-iam-policy-binding "${GCP_PROJECT}" \
  --member="serviceAccount:${SA_EMAIL}" \
  --role="projects/${GCP_PROJECT}/roles/${GCP_ROLE_ID}" \
  --condition=None \
  --quiet

# ------------------------------------------------------------------
# 5. Mint a service-account key
#    (F5's gcp_cred_file resource and GOOGLE_APPLICATION_CREDENTIALS both
#    need an actual key today - this is the same key.json the F5 doc
#    instructs you to paste into the console's Secret Info field.)
# ------------------------------------------------------------------
echo "==> Creating key at ${KEY_FILE}..."
gcloud iam service-accounts keys create "${KEY_FILE}" --iam-account="${SA_EMAIL}"
chmod 600 "${KEY_FILE}"

# ------------------------------------------------------------------
# 6. Wire the result into the TF_VAR_* names this repo already expects
# ------------------------------------------------------------------
if base64 -w0 "${KEY_FILE}" >/tmp/.b64key.$$ 2>/dev/null; then
  B64_KEY="$(cat /tmp/.b64key.$$)"
  rm -f /tmp/.b64key.$$
else
  B64_KEY="$(base64 -i "${KEY_FILE}")" # BSD/macOS base64 doesn't wrap by default
fi

KEY_FILE_ABS="$(cd "$(dirname "${KEY_FILE}")" && pwd)/$(basename "${KEY_FILE}")"

cat > "${ENV_FILE}" <<EOF
#!/usr/bin/env bash
# Generated by f5xc-gcp-iam-setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source before terraform plan/apply: source ${ENV_FILE}
# Add your F5XC vars (TF_VAR_f5xc_api_url, TF_VAR_f5xc_api_p12_file,
# TF_VAR_f5xc_tenant, VES_P12_PASSWORD) separately - this only covers GCP.

export GOOGLE_APPLICATION_CREDENTIALS="${KEY_FILE_ABS}"
export TF_VAR_gcp_project_id="${GCP_PROJECT}"
export TF_VAR_gcp_service_account_key_b64="${B64_KEY}"
EOF
chmod 600 "${ENV_FILE}"

echo
echo "Done."
echo "  Service account: ${SA_EMAIL}"
echo "  Role:             projects/${GCP_PROJECT}/roles/${GCP_ROLE_ID}"
echo "  Key file:         ${KEY_FILE_ABS}   (already covered by .gitignore: sa-key*, *.json)"
echo "  Env file:         ${ENV_FILE}       (already covered by .gitignore: .f5xc-env.sh)"
echo
echo "Next: source ${ENV_FILE}, add your F5XC env vars, then terraform plan"